### ISSUE TITLE
Introduce ModulemdDefaultUnit model class

### ISSUE THREAD

**Issue by rbikar** [release-engineering/pubtools-pulplib#58]
#### Summary
Introduce new model class for Modulemd defaults unit. It should be named ModulemdDefaultUnit and it should have at least following attributes:

- name (str)
- stream (str)
- profiles (dict, e.g. {'4.01': ['common']})

And also it should have property e.g. named  _name_profiles_
 which creates str with flattened profiles and pretends name.
See current implementation: 
https://github.com/release-engineering/ubi-population-tool/blob/c7d3647f007c9cb98855c750994cd51407964c80/ubipop/_pulp_client.py#L397
It is used in comparison method in ubipop.

#### Issue Type
- Feature Request

#### Current behavior
Class in question is not implemented yet.

#### Desired behavior
- model class ModulemdDefaultUnit is implemented with behavior explained in description.

**Comment by rohanpm** [comment]
I would rather the name_profiles attribute stays in ubipop as it seems to be only a helper for ubipop implementation details.

**Comment by rbikar** [comment]
This has been already implemented in 2.4.0 and 2.6.0. Closing.
