### ISSUE TITLE
Extend RpmUnit class (srpm fname, is_modular, vercmp)

### ISSUE THREAD

**Issue by rbikar** [release-engineering/pubtools-pulplib#59]
#### Summary
The goal of this issue is to extend current implementation of RpmUnit model class.
It should offer following attrs:

- srpm filename (str)
- is_modular (bool) - this attr is True, if rpm is referenced by any Modulemd unit in repository, False otherwise. Value taken from Pulp can be unreliable therefore ubipop currently does calculation of this on its own.
- method for comparison by evr: Ubipop now uses function labelCompare from rpm python bindings, see https://github.com/release-engineering/ubi-population-tool/blob/c7d3647f007c9cb98855c750994cd51407964c80/ubipop/_pulp_client.py#L331, this also requires adding rpm-py-installer into install_requires but as this python package does not have rpm, this req needs to be manually removed while building rpm -> so spec file must be updated as well. For more context see Q6 https://github.com/junaruga/rpm-py-installer/blob/master/docs/users_guide.md 

#### Issue Type
- Feature Request

#### Current behavior
RpmUnit is missing several attrs and cmp method required in ubipop.

#### Desired behavior
RpmUnit class is extended by requirements described in summary.
- attrs: srpm_filename, is_modular
- cmp method

**Comment by rohanpm** [comment]
> is_modular (bool) - this attr is True, if rpm is referenced by any Modulemd unit in repository, False otherwise. Value taken from Pulp can be unreliable therefore ubipop currently does calculation of this on its own.

I feel like that would be quite difficult to implement in the general case - it means that you can't initialize is_modular properly unless you've searched and parsed all the modulemd in the repo.  That's a pretty major thing to do implicitly when someone searched for RPMs.

Perhaps we can trust the field from Pulp now, per the fix mentioned on https://github.com/release-engineering/ubi-population-tool/issues/94#issuecomment-501467660.

**Comment by rbikar** [comment]
Note: srpm filename attr has already been implemented.

**Comment by rbikar** [comment]
Checking relevancy of this issue:
- srpm_filename on RpmUnit -> implemented in pubtools-pulplib.
- is_modular -> currently not needed, and it's still manually calculated in ubi-manifest project which is the most accurate method.
- cmp method for rpms -> currently not needed in pubtools-pulplib. Recently it was moved from ubipop to ubi-manifest project.

Closing issue.
