### ISSUE TITLE
Extend YumRepository model class with attrs from repo notes

### ISSUE THREAD

**Issue by rbikar** [release-engineering/pubtools-pulplib#61]
#### Summary
Goal of this issue is to extend YumRepository model class with attrs from repo notes:
- arch
- content_set
- platform_full_version
- ubi_population
- population_sources

#### Issue Type
- Feature Request

#### Current behavior
There missing attrs in YumRepository class that are requried for ubipop.

#### Desired behavior
YumRepository class has attrs: 
- arch
- content_set
- platform_full_version
- ubi_population
- population_sources

**Comment by rohanpm** [comment]
Based on the online docs at https://release-engineering.github.io/pubtools-pulplib/api/yum.html , looks like this has been implemented some time ago.
