### ISSUE TITLE
Extend Repository.remove_content to accept criteria 

### ISSUE THREAD

**Issue by rbikar** [release-engineering/pubtools-pulplib#62]
#### Summary

The goal is this issue to extend method Repository.remove_content so it accepts also criteria parameter. Now it removes (unassociates) all content in repository of given type. We need to extend this so we can unassociate specific rpms, modulemd units and modulemd defaults units from repo. This will also require extending  _do_unassociate methods in [fake,client]/client.py.

#### Issue Type
- Feature Request

#### Current behavior

Repository.remove_content removes all content of given type.

#### Desired behavior
Repository.remove_content:
- accepts criteria parameter and it needs to support matching:
- S/RPMS by exact match on filename field
- ModuleMd unit by exact match on all following fields 'name', 'context', 'version', 'stream', 'arch
- ModuleMd Defaults unit by exact match on all following fields: 'name', 'stream'
- it can used for unassociation of s/rpms, modulemd and modulemd defaults units from given repo

#### Use case

`repo1.remove_content(criteria=Critera(...))
`

**Comment by rohanpm** [comment]
@rbikar  could you elaborate which kinds of criteria will be needed for ubipop use-cases?

It says "specific rpms, modulemd units and modulemd defaults units", does it mean you'd always be providing all the fields in the unit key and doing matching by equality (not e.g. "version less than" for RPMs, or similar.)

**Comment by rbikar** [comment]
@rohanpm 
Sure, ubipop does now matching by equality on specific fields. I'll add it to issue description.
